#!/bin/bash

# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2025 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

test -f .env && source $_

BOLT_LAYER_SETUP_SCRIPT=$(realpath -se "${BASH_SOURCE[0]}")
BOLT_SETUP_SCRIPT=deps/bolt/setup-environment

if [ ! -f ${BOLT_SETUP_SCRIPT} ]; then
  "${BOLT_LAYER_SETUP_SCRIPT%/*}/repo-sync"
fi

if [ -f ${BOLT_SETUP_SCRIPT} ]; then
  source ${BOLT_SETUP_SCRIPT}
  bolt_layer_setup "${BOLT_LAYER_SETUP_SCRIPT%/*}"
fi

unset BOLT_SETUP_SCRIPT
unset BOLT_LAYER_SETUP_SCRIPT
